### ISSUE TITLE
Allow to edit and delete workout log entries

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/flutter#32]
At the moment it is not possible to edit or delete workout logs. There should be an option to do this, e.g. in the workout log page

**Comment by TaarnStar** [comment]
Hi, I am fairly new to flutter but would like to try and do this issue. Could I be assigned to this issue?

Thanks

**Comment by rolandgeider** [comment]
It's yours!

I would suggest first implementing deleting the entries (if you want, open a new issue for this). As for the editing, don't allow the users to edit the exercise, just the other attributes. Also, since you need a backend for this, I can give you access to the test server, then you don't need to setup docker or anything, just write me over discord or per mail

**Comment by TaarnStar** [comment]
@rolandgeider I sent you an email for access to the test server :)

**Comment by TaarnStar** [comment]
@rolandgeider I looked a bit in the code, I will open a new issue for delete option, but just to confirm for edit option, user should be able to edit all the attributes except the exercise?

So that would be name, description, category and images? The rest of the options shouldn't be editable?

**Comment by rolandgeider** [comment]
Workout logs have no images, but yes everything besides the exercise itself should be editable

**Comment by artchiee** [comment]
Hi @rolandgeider , @TaarnStar  ; is this issue has been solved!? currently still open! but i saw that it's related to other 'issue" that have been closed / or merged!?  Ps: i have not cloned nor tried the app yet!! . Thanks!

**Comment by toruwatanbe** [comment]
Hi @TaarnStar ,
I am new to Flutter and Open Source, I really need your help figuring things out and want to discuss with you regarding this specific issue, can you please share your email, or ping me on : jagrutdamdhar.mit@gmail.com. Thanks.

**Comment by Ganesh4326** [comment]
Hello, can I try this one?

**Comment by rolandgeider** [comment]
Hi @Ganesh4326 ! Sure, go ahead!

**Comment by ExZylan** [comment]
Hi, it looks like the implementation of editing the workout logs is broken. I have tried with a fresh install to discard that the problem was from my installation and it still happens. When I try to edit or delete one of the reps of an exercise it takes me to an error page.

**Comment by afsheen-nadaf** [comment]
Hi, I saw that this issue is still open and hasn’t had updates in a while. I’m new to Flutter, but I’d like to work on adding the option to edit and delete workout log entries. Could I take this issue? If someone else is already working on it, that’s fine too, just let me know.

Thanks!

**Comment by raza-khan0108** [comment]
Hi, i saw this issue open and i have built multiple production level apps, can i try to solve this issue. I have worked on this problem before

**Comment by manavsep** [comment]
Hello, I know Flutter on a decent level. I would like to try this as my first open source issue. May I be assigned to this? :)

**Comment by rolandgeider** [comment]
Hey @manavsep! 

Sure, but I would ask you to wait till we merge this monster of an issue #1183, which will be the next version, as it touches how the objects are persisted, then we won't have to do it twice. Hopefully this will happen in the next two weeks

**Comment by manavsep** [comment]
Is it ready to work on now?

**Comment by rolandgeider** [comment]
sorry, it seems this is already implemented, we probably just didn't link the PR properly
